### ISSUE TITLE
Milestone suggestions

### ISSUE THREAD

**Issue by ebeshero** [spookybeetle/bojack#5]
- [ ] Did you set up GitHub Pages on this repo? (I'm not seeing a published website, but I can see @SavannahRicks 's files of cours) @spookybeetle 

- [ ] Nice work with the scripts! I think you could probably regex the stuff in square brackets `\[.+?\]` to separate it out from spoken stuff (aren't those descriptions/stage cues?)

- [ ] You usually don't have speakers' names, but you will certainly see characters and other _named entities_ mentioned. And Python/spaCy can help you find them. Here's something to try:
     - [ ] Try adapting this Python script we ran last year of a collection of Grimm's fairy tales: it's adapted to look for named entities. (You could also study particular parts of speech of interest--very similar code from our January/February Python exercises): 
     https://github.com/newtfire/textAnalysis-Hub/blob/main/Class-Examples/Python/nlp-spaCy/nlp-sentences.py 
   
    - [ ] You'll be able to output a list of these--and we can save those to an output file. WE can then map them in to your XML for the scripts with an XSLT identity transformation script: I can help with that!
